id: P009327
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG13832
  title: ཐེག་པ་ཆེན་པོ་རྒྱུད་བླ་མའི་ཚིག་འགྲེལ།
  author: ''
  volumes:
    8bf91f7c72f74ad4b90e79dc46e606fe:
      image_group_id: I1KG16121
      title: ''
      volume_number: 1
      total_pages: 456
      base_file: v001.txt
